yong/views/car_view.py
from flask import Blueprint, render_template, request
import os
from flask import Blueprint, render_template, request, flash, url_for, redirect
import uuid
from yong.utils import Utils
from yong.models.car_predict_model import CarPredict
from yong.models.car_model import Car
from yong.models.pagination_model import Pagination
from yong.models.car_data_model import CarData
from flask_login import current_user, login_required
#from yong.config import BUCKET_PATH
BUCKET_PATH = os.environ['BUCKET_PATH']

bp = Blueprint('car', __name__, url_prefix='/car')
cardata = CarData.get_data()


@bp.route('/predict', methods=['GET','POST'])
def predict():
    if request.method =='POST':
        manufact = request.form['manufact']
        model = request.form['model']
        age = int(request.form['age'])
        odo = int(request.form['odo'].replace(',', ''))
        fuel = request.form['fuel']
        color = request.form['color']
        car = CarPredict(manufact,model,age,odo,fuel,color)                   
        price = Utils.predict_price(model, age, odo, fuel, color)        
        price_newcar = int(Utils.predict_price(model, 2021, 0, fuel, color)*1.1)
        price_1 = Utils.predict_price(model, age-1, odo, fuel, color)
        price_3 = Utils.predict_price(model, age-3, odo, fuel, color)
        price_5 = Utils.predict_price(model, age-5, odo, fuel, color)
        price_list = [price_newcar, price, price_1, price_3, price_5]
        mean_odo = int(cardata[cardata['age'] == age]['odo'].mean())
        try:
            mean_model_odo = int(cardata[(cardata['age'] == age) & (cardata['model'] == model)]['odo'].mean())
        except:
            mean_model_odo = mean_odo
        return render_template('car/predict_car.html', car=car, model=model, odo=odo, price_list=price_list, mean_odo=mean_odo, mean_model_odo=mean_model_odo)
    price_list=[0, 0, 0, 0, 0]
    return render_template('car/predict_car.html', price_list=price_list)


@bp.route('/predict/report/<model>', methods=['GET','POST'])
def report(model):
    cardata = CarData.get_data()
    price_age_list = []
    price_odo_list = []
    model_list = []
    models=cardata['model'].unique()
    for model_ in models:model_list.append(len(cardata[cardata['model']==model_])) 
    for age in range(2000,2022):price_age_list.append(Utils.predict_price(model,age,0,'가솔린','black'))
    for odo in range(0,160000,10000):price_odo_list.append(Utils.predict_price(model,2021,odo,'가솔린','black'))
    return render_template('car/report_car.html', model_list=model_list, model=model, price_age_list=price_age_list, price_odo_list=price_odo_list)    


@bp.route('/list/', defaults={'current_page': 1})
@bp.route('/list/<int:current_page>', methods=['GET','POST'])
def _list(current_page):
    try:
        Car.get_size()
    except:
        None
    list_size = Car.get_size()
    page_size = 9
    current_page_count = 3
    pagination = Pagination(list_size,page_size,current_page_count)
    page_count = pagination.page_count
    if current_page > page_count:
        current_page = page_count
    elif current_page <= 0:
        current_page = 1
    car_list = Car.get_page((current_page-1)*page_size,page_size)
    start_page = int((current_page-1)/current_page_count)*current_page_count+1
    if (page_count-start_page) < current_page_count:
        page_length = (page_count-start_page) + 1
    else:
        page_length = current_page_count
    return render_template('car/car_list.html',list_size=list_size, car_list=car_list, start_page=start_page, page_length=page_length, current_page=current_page)


@bp.route('/create', methods=['GET','POST'])
@login_required
def create():
    if request.method == 'POST':
        manufact = request.form['manufact']
        model = request.form['model']
        age = int(request.form['age'])
        odo = int(request.form['odo'].replace(',', ''))
        fuel = request.form['fuel']
        color = request.form['color']
        price = int(request.form['price'].replace(',', ''))
        comment = request.form['comment']
        user_id = current_user.user_id
        file = request.files['file']
        predicted_price = Utils.predict_price( model, age, odo, fuel, color)
        if file and Utils.check_allowed_file(file.filename):
            img_uid = uuid.uuid4().hex 
            img_url = BUCKET_PATH + img_uid
            Car.create(user_id,manufact, model,age,odo,fuel,color,price,comment,img_url,predicted_price)
            Utils.upload_img(img_uid, file) 
            return redirect(url_for('car._list'))
        elif not file:
            flash('차량 사진을 선택하세요.')
            return render_template('car/add_car.html')
        elif not Utils.check_allowed_file(file.filename): 
            flash('이미지 파일만 업로드 가능합니다. (jpg, jpeg, png)')
            return render_template('car/add_car.html')
    return render_template('car/add_car.html')


@bp.route('/detail/<int:car_id>', methods=['GET','POST'])
def detail(car_id):
    car = Car.get(car_id)
    return render_template('car/car_detail.html',car=car)


@bp.route('/delete/<int:car_id>')
@login_required
def delete(car_id):
    car = Car.get(car_id)
    img_uid = car.get_img_url().replace(BUCKET_PATH, '')
    Utils.delete_img(img_uid)
    Car.delete(car_id)   
    return redirect(url_for('car._list'))

yong/templates/car/add_car.html
{% extends 'base.html' %}
{% block content %}
{% with messages = get_flashed_messages() %}
 {% if messages %}
  <script>
   alert("{{messages[-1]}}")
  </script>
  {% endif %}
{% endwith %}
<div class="row">
<form enctype="multipart/form-data" class="col-5 d-grid gap-2" method="POST" action="{{ url_for('car.create') }}"> 
    <select required="required" class="form-select p-2" id="manufact" name="manufact" >
      <option value="">제조사 선택</option>
      <option value="현대">현대</option>
      <option value="제네시스">제네시스</option>
      <option value="기아">기아</option>
      <option value="르노삼성">르노삼성</option>
      <option value="쌍용">쌍용</option>
      <option value="GM대우">GM대우</option>
      <option value="벤츠">벤츠</option>
      <option value="BMW">BMW</option>
      <option value="아우디">아우디</option>
      <option value="폭스바겐">폭스바겐</option>
    </select>
    <select required="required" class="form-select p-2" id="model" name="model">
      <option value="">모델 선택</option>
      <!-- 현대 -->
      <option value="아반떼" class="현대">아반떼</option>
      <option value="쏘나타" class="현대">쏘나타</option>
      <option value="그랜저" class="현대">그랜저</option>
      <!-- 제네시스 -->
      <option value="G70" class="제네시스">G70</option>
      <option value="G80" class="제네시스">G80</option>     
      <!-- 기아 -->
      <option value="K3" class="기아">K3</option>
      <option value="K5" class="기아">K5</option>
      <option value="K7" class="기아">K7</option>
      <!-- 르노삼성 -->
      <option value="SM3" class="르노삼성">SM3</option>
      <option value="SM5" class="르노삼성">SM5</option>
      <option value="SM6" class="르노삼성">SM6</option>
      <option value="SM7" class="르노삼성">SM7</option>
      <!-- 쌍용 -->
      <option value="티볼리" class="쌍용">티볼리</option>
      <option value="코란도" class="쌍용">코란도</option>
       <!-- GM대우 -->
      <option value="크루즈" class="GM대우">크루즈</option>
      <option value="말리부" class="GM대우">말리부</option>
      <!-- 벤츠  -->
      <option value="C클래스" class="벤츠">C클래스</option>
      <option value="E클래스" class="벤츠">E클래스</option>
      <option value="S클래스" class="벤츠">S클래스</option>
      <!-- BMW  -->
      <option value="3시리즈" class="BMW">3시리즈</option>
      <option value="5시리즈" class="BMW">5시리즈</option>
      <option value="7시리즈" class="BMW">7시리즈</option>
      <!-- 아우디  -->
      <option value="A4" class="아우디">A4</option>
      <option value="A6" class="아우디">A6</option>
      <option value="A7" class="아우디">A7</option>
      <!-- 폭스바겐  -->
      <option value="골프" class="폭스바겐">골프</option>
      <option value="티구안" class="폭스바겐">티구안</option>
      <option value="파사트" class="폭스바겐">파사트</option>      
    </select>
    <select required="required" class="form-select p-2" id="age" name="age">
      <option value="">연식 선택</option>
      <option value="2021">2021년식</option>
      <option value="2020">2020년식</option>
      <option value="2019">2019년식</option>
      <option value="2018">2018년식</option>
      <option value="2017">2017년식</option>
      <option value="2016">2016년식</option>
      <option value="2015">2015년식</option>
      <option value="2014">2014년식</option>
      <option value="2013">2013년식</option>
      <option value="2012">2012년식</option>
      <option value="2011">2011년식</option>
      <option value="2010">2010년식</option>
      <option value="2009">2009년식</option>
      <option value="2008">2008년식</option>
      <option value="2007">2007년식</option>
      <option value="2006">2006년식</option>
      <option value="2005">2005년식</option>
      <option value="2004">2004년식</option>
      <option value="2003">2003년식</option>
      <option value="2002">2002년식</option>
      <option value="2001">2001년식</option>
      <option value="2000">2000년식</option>
    </select>
    <div class="input-group">
      <input required="required p-2" onkeyup="inputNumberFormat(this)" name="odo" id="odo" type="text" class="form-control" placeholder="주행거리" aria-describedby="basic-addon2">
      <span class="input-group-text p-2" id="basic-addon2">km</span>
    </div>
    <select required="required" class="form-select p-2" id="fuel" name="fuel">
      <option value="">연료타입 선택</option>
      <option value="가솔린">가솔린</option>
      <option value="디젤">디젤</option>
      <option value="LPG">LPG</option>
      <option value="hybird">하이브리드</option>
    </select>
    <select required="required" class="form-select p-2" id="color" name="color">
      <option value="">색상 선택</option>
      <option value="black">검정색</option>
      <option value="white">흰색</option>
      <option value="gray">은색&회색</option>
      <option value="other">기타</option>
    </select>
    <div class="input-group">
          <input required="required p-2" onkeyup="inputNumberFormat(this)" name="price" id="price" type="text" class="form-control" placeholder="가격" aria-describedby="basic-addon2">
          <span class="input-group-text p-2" id="basic-addon2">만원</span>
    </div>
    <div class="form-group">
          <label for="comment">상세 정보</label>
          <textarea class="form-control" name="comment" id="comment" rows="10" onKeyUp="javascript:fnChkByte(this,'1000')"></textarea>
    </div>
      <label for="comment">사진 등록 (필수)</label>
      <div class="input-group mb-3">
        <input type="file" name = 'file' class="form-control" accept="image/png, image/jpeg" >
      </div>
    <button type="submit" class="p-3 btn btn-primary">등록하기</button>
  </form>
</div>


<script>
  let manu_select = document.getElementById('manufact');
  let model_select = document.getElementById('model');
  for(var item of model_select){
            if(item.className != '현대'){
                item.style.display = 'none';
            }
        }
  manu_select.onchange = function(){
      var selectClass = manu_select.value;
      for(var item of model_select){
        if(item.className == selectClass){          
          item.style.display ='inline';          
        }else{          
          item.style.display = 'none';
        }
      }
      firstVal = document.getElementsByClassName(selectClass)
      model_select.value = firstVal[0].value
  }
</script>
<script type="text/javascript">
    function comma(str) {
        str = String(str);
        return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
    }
    function uncomma(str) {
        str = String(str);
        return str.replace(/[^\d]+/g, '');
    } 
    function inputNumberFormat(obj) {
        obj.value = comma(uncomma(obj.value));
    } 
    function inputOnlyNumberFormat(obj) {
        obj.value = onlynumber(uncomma(obj.value));
    }
    function onlynumber(str) {
	    str = String(str);
	    return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g,'$1');
	}
</script>
<script>
  function fnChkByte(obj, maxByte)
  {
      var str = obj.value;
      var str_len = str.length;
      var rbyte = 0;
      var rlen = 0;
      var one_char = "";
      var str2 = "";
      for(var i=0; i<str_len; i++)
      {
          one_char = str.charAt(i);
          if(escape(one_char).length > 4) {
              rbyte += 2;                                         //한글2Byte
          }else{
              rbyte++;                                            //영문 등 나머지 1Byte
          }
          if(rbyte <= maxByte){
              rlen = i+1;                                          //return할 문자열 갯수
          }
      }
      if(rbyte > maxByte)
      {
          // alert("한글 "+(maxByte/2)+"자 / 영문 "+maxByte+"자를 초과 입력할 수 없습니다.");
          alert("글 용량은 최대 " + maxByte + "byte를 초과할 수 없습니다.")
          str2 = str.substr(0,rlen);                                  //문자열 자르기
          obj.value = str2;
          fnChkByte(obj, maxByte);
      }
      else
      {
          document.getElementById('byteInfo').innerText = rbyte;
      }
  }
</script>
{% endblock %}

yong/templates/car/car_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-5">  
        <img src={{car.img_url}} class="img-fluid">
    </div>
    <div class="col-6">  
        <h1 class="my-3 fw-bold">{{car.manufact}} {{car.model}} </h1>
        <p class="my-3 text-muted">{{car.age}}년식 | {{'{:,}'.format(car.odo)}}km | {{car.fuel}} </p>
        <h2 class="my-3 fw-bold">판매가격 <strong class="text-primary">{{'{:,}'.format(car.price)}}만원</strong></h2>
        <hr class="my-5">
        <h4 class="my-5">{{car.comment}}</h4>
        {% if current_user.user_id == car.user_id %}
        <div class="my-3">
            <a href="{{ url_for('car.delete', car_id=car.car_id, user_id=car.user_id) }}"
               class="delete btn btn-sm btn-outline-secondary">삭제</a>
        </div>
       {% endif %}
    </div>
{% endblock %}

yong/templates/car/car_form.html
{% extends "base.html" %}
{% block content %}



<div class="row">

  <form class="m-1 h-75 col-3 d-grid gap-1" method="POST" action="{{ url_for('car.form') }}"> <!-- note action -->
   

    <select required="required" class="form-select" id="manufact" name="manufact" >
      <option value="">제조사 선택</option>
      <option value="현대">현대</option>
      <option value="기아">기아</option>
      <option value="르노삼성">르노삼성</option>
      <option value="쌍용">쌍용</option>
      <option value="GM대우">GM대우</option>
      <option value="벤츠">벤츠</option>
      <option value="BMW">BMW</option>
      <option value="아우디">아우디</option>
      <option value="폭스바겐">폭스바겐</option>
    </select>


    <select required="required" class="form-select" id="model" name="model">
      <option value="">모델 선택</option>
      <!-- 현대 -->
      <option value="아반떼" class="현대">아반떼</option>
      <option value="쏘나타" class="현대">쏘나타</option>
      <option value="그랜저" class="현대">그랜저</option>
      <option value="G70" class="현대">G70</option>
      <option value="G80" class="현대">G80</option>
      
      <!-- 기아 -->
      <option value="K3" class="기아">K3</option>
      <option value="K5" class="기아">K5</option>
      <option value="K7" class="기아">K7</option>
      
      <!-- 르노삼성 -->
      <option value="SM3" class="르노삼성">SM3</option>
      <option value="SM5" class="르노삼성">SM5</option>
      <option value="SM6" class="르노삼성">SM6</option>
      <option value="SM7" class="르노삼성">SM7</option>

      <!-- 쌍용 -->
      <option value="티볼리" class="쌍용">티볼리</option>
      <option value="코란도" class="쌍용">코란도</option>
      
       <!-- GM대우 -->
      <option value="크루즈" class="GM대우">크루즈</option>
      <option value="말리부" class="GM대우">말리부</option>

      <!-- 벤츠  -->
      <option value="C클래스" class="벤츠">C클래스</option>
      <option value="E클래스" class="벤츠">E클래스</option>
      <option value="S클래스" class="벤츠">S클래스</option>

      <!-- BMW  -->
      <option value="3시리즈" class="BMW">3시리즈</option>
      <option value="5시리즈" class="BMW">5시리즈</option>
      <option value="7시리즈" class="BMW">7시리즈</option>

      <!-- 아우디  -->
      <option value="A4" class="아우디">A4</option>
      <option value="A6" class="아우디">A6</option>
      <option value="A7" class="아우디">A7</option>

      <!-- 폭스바겐  -->
      <option value="골프" class="폭스바겐">골프</option>
      <option value="티구안" class="폭스바겐">티구안</option>
      <option value="파사트" class="폭스바겐">파사트</option>      
    </select>


    <select required="required" class="form-select" id="age" name="age">
      <option value="">연식 선택</option>
      <option value="2021">2021년식</option>
      <option value="2020">2020년식</option>
      <option value="2019">2019년식</option>
      <option value="2018">2018년식</option>
      <option value="2017">2017년식</option>
      <option value="2016">2016년식</option>
      <option value="2015">2015년식</option>
      <option value="2014">2014년식</option>
      <option value="2013">2013년식</option>
      <option value="2012">2012년식</option>
      <option value="2011">2011년식</option>
      <option value="2010">2010년식</option>
      <option value="2009">2009년식</option>
      <option value="2008">2008년식</option>
      <option value="2007">2007년식</option>
      <option value="2006">2006년식</option>
      <option value="2005">2005년식</option>
      <option value="2004">2004년식</option>
      <option value="2003">2003년식</option>
      <option value="2002">2002년식</option>
      <option value="2001">2001년식</option>
      <option value="2000">2000년식</option>
    </select>



    <div class="input-group">
      <input required="required" onkeyup="inputNumberFormat(this)" name="odo" id="odo" type="text" class="form-control" placeholder="주행거리" aria-label="Recipient's username" aria-describedby="basic-addon2">
      <span class="input-group-text p-2" id="basic-addon2">km</span>
    </div>

    

    
    <select required="required" class="form-select p-2" id="fuel" name="fuel">
      <option value="">연료타입 선택</option>
      <option value="가솔린">가솔린</option>
      <option value="디젤">디젤</option>
      <option value="LPG">LPG</option>
      <option value="hybird">하이브리드</option>
    </select>


    <select required="required" class="form-select p-2" id="color" name="color">
      <option value="">색상 선택</option>
      <option value="black">검정색</option>
      <option value="white">흰색</option>
      <option value="gray">은색&회색</option>
      <option value="other">기타</option>
    </select>


    <button type="submit" class="btn btn-primary p-3">검색하기</button>
  </form>


{% if price %}
  <div class="col-7 m-5 bg-light">  
      <h1 class="fw-bold">{{manufact}} {{model}} <span class="text-muted">차량 정보입니다.</span></h1>
      <img src="/static/car_image/{{manufact}}_{{model}}.jpg" alt="My Image" width="500" height="300">
      <p class="text-muted">{{age}}년식 | {{odo}}km | {{fuel}}</p>
      <h2 class="fw-bold">해당 매물은 <strong class="text-primary">{{price}}만원</strong>으로 예측 됩니다.</h2>
  </div>


{% else %}

<div class="col-7 bg-light ">
  
  
  <div class="px-4 py-5  text-center">

    <h1 class="p-3 display-5 fw-bold">검색 해보세요!</h1>
    <div class="mx-auto">
      <p class="p-2 lead mb-4">차량정보를 입력하면, 머신러닝 기술을 이용하여 중고차 가격을 예측해 주는 서비스입니다. </p>
    </div>
  </div>

      
</div>
  

{% endif %}

</div>


<script>

  let manu_select = document.getElementById('manufact');
  let model_select = document.getElementById('model');
  for(var item of model_select){
            if(item.className != '현대'){
                item.style.display = 'none';
            }
        }

  manu_select.onchange = function(){
           
      var selectClass = manu_select.value;
      
      for(var item of model_select){
        if(item.className == selectClass){          
          item.style.display ='inline';          
        }else{          
          item.style.display = 'none';
        }
      }

      firstVal = document.getElementsByClassName(selectClass)
      model_select.value = firstVal[0].value

  }



</script>

<script type="text/javascript">
    function comma(str) {
        str = String(str);
        return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
    }

    function uncomma(str) {
        str = String(str);
        return str.replace(/[^\d]+/g, '');
    } 
    
    function inputNumberFormat(obj) {
        obj.value = comma(uncomma(obj.value));
    }
    
    function inputOnlyNumberFormat(obj) {
        obj.value = onlynumber(uncomma(obj.value));
    }
    
    function onlynumber(str) {
	    str = String(str);
	    return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g,'$1');
	}
</script>



{% endblock %}

yong/templates/car/car_list.html
{% extends "base.html" %}
{% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }

  #index {
  border-radius: 20px;
  }
</style>


<section class="py-5 text-center container">
  <button id="index" type="button" class="btn btn-dark" disabled data-bs-toggle="button" autocomplete="off">총 {{list_size}} 대의 차량이 있습니다.</button>
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">매물을 등록하세요!</h1>
      <p class="lead text-muted">사람들이 웹사이트에 등록한 중고차 매물을 구경할 수 있습니다.</p>
      <p>
        <a href="{{ url_for('car.create') }}" class="btn btn-primary my-2">매물 등록하기</a> 
      </p>
    </div>
  </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
{% if car_list %}
{% for car in car_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{car.img_url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img"  preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#55595c"/></img>
            <div class="card-body">
              <p class="card-text fw-bold">{{car.manufact}} {{car.model}}</p>
              <p class="card-text text-muted">{{car.age}}년식 | {{'{:,}'.format(car.odo)}}km | {{car.fuel}}</p>
              <p class="card-text text-primary">{{'{:,}'.format(car.price)}}만원</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" onclick="location.href='{{url_for('car.detail', car_id=car['car_id'])}}'" class="btn btn-sm btn-outline-secondary">상세정보</button>                 
                </div>
                {% if car.price<=car.predicted_price*0.4 %}
                <span title="해당 매물의 적정 시세는 {{'{:,}'.format(car.predicted_price)}}만원 입니다." data-toggle="tooltip" data-placement="top" class="badge rounded-pill bg-danger">허위매물 위험</span>
                {% elif (car.price>car.predicted_price*0.4)and(car.price<=car.predicted_price*0.6) %}
                <span title="해당 매물의 적정 시세는 {{'{:,}'.format(car.predicted_price)}}만원 입니다." data-toggle="tooltip" data-placement="top" class="badge rounded-pill bg-warning">허위매물 주의</span>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
 {% endfor %}
 {% else %}
          <h1>매물이 없습니다. 매물을 등록 해 주세요</h1>
 {% endif %}
      </div>
    </div>
  </div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="{{url_for('car._list', current_page=current_page-1)}}">이전</a></li>
    {% for page_num in range(start_page,(start_page+page_length)) %}
    {% if page_num==current_page %}
    <li class="page-item active"><a class="page-link" href="{{url_for('car._list', current_page=page_num)}}")>{{page_num}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{url_for('car._list', current_page=page_num)}}")>{{page_num}}</a></li>
    {% endif %}
    {% endfor %}
    <li class="page-item"><a class="page-link" href="{{url_for('car._list', current_page=current_page+1)}}">다음</a></li>
  </ul>
</nav>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script>
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()
		})
</script>
{% endblock %}