yong/views/answer_view.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from yong.models.answer_model import Answer


bp = Blueprint('answer', __name__, url_prefix='/')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    content = request.form['content']
    user_id = current_user.user_id
    Answer.create(user_id, question_id, content)
    return redirect(url_for('question.detail', question_id=question_id))


@bp.route('/delete/answer/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.get(answer_id)
    Answer.delete(answer_id)
    return redirect(url_for('question.detail', question_id=answer.question_id))

yong/views/question_view.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from ..forms import QuestionForm
from yong.models.question_model import Question
from yong.models.answer_model import Answer
from yong.models.pagination_model import Pagination


bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        title = request.form['title']
        content = request.form['content']
        user_id = current_user.user_id
        Question.create(user_id, title, content)
        return redirect(url_for('question._list'))
    return render_template('question/add_question.html', form=form)


@bp.route('/list/', defaults={'current_page': 1})
@bp.route('/list/<int:current_page>')
def _list(current_page):
    try:
        Question.get_size()
    except:
        None
    list_size = Question.get_size()
    page_size = 5
    current_page_count = 3
    pagination = Pagination(list_size,page_size,current_page_count)
    page_count = pagination.page_count
    if current_page > page_count:
        current_page = page_count
    elif current_page <= 0:
        current_page = 1
    question_list = Question.get_page((current_page-1)*page_size,page_size)
    #question_list = Question.get_list()
    start_page = int((current_page-1)/current_page_count)*current_page_count+1
    if (page_count-start_page) < current_page_count:
        page_length = (page_count-start_page) + 1
    else:
        page_length = current_page_count
    return render_template('question/question_list.html', question_list=question_list, start_page=start_page, page_length=page_length, current_page=current_page)


@bp.route('/<int:question_id>')
def detail(question_id):
    question = Question.get(question_id)
    answer_list = Answer.get_list(question_id)
    return render_template('question/question_detail.html', question=question, answer_list=answer_list)


@bp.route('/modify/<int:question_id>', methods=['GET', 'POST'])
@login_required
def modify(question_id):
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        title = request.form['title']
        content = request.form['content']
        Question.modify(title, content, question_id)
        return redirect(url_for('main.home'))
    return render_template('question/add_question.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    Question.delete(question_id)
    return redirect(url_for('question._list'))

yong/templates/question/add_question.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
<h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post" class="post-form">
        {{ form.hidden_tag() }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
       <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" onKeyUp="javascript:fnChkByte(this,'200')">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="5" onKeyUp="javascript:fnChkByte(this,'1000')"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>


<script>
    function fnChkByte(obj, maxByte)
    {
        var str = obj.value;
        var str_len = str.length;
        var rbyte = 0;
        var rlen = 0;
        var one_char = "";
        var str2 = "";
        for(var i=0; i<str_len; i++)
        {
            one_char = str.charAt(i);
            if(escape(one_char).length > 4) {
                rbyte += 2;                                         //한글2Byte
            }else{
                rbyte++;                                            //영문 등 나머지 1Byte
            }
            if(rbyte <= maxByte){
                rlen = i+1;                                          //return할 문자열 갯수
            }
        }
        if(rbyte > maxByte)
        {
            // alert("한글 "+(maxByte/2)+"자 / 영문 "+maxByte+"자를 초과 입력할 수 없습니다.");
            alert("글 용량은 최대 " + maxByte + "byte를 초과할 수 없습니다.")
            str2 = str.substr(0,rlen);                                  //문자열 자르기
            obj.value = str2;
            fnChkByte(obj, maxByte);
        }
        else
        {
            document.getElementById('byteInfo').innerText = rbyte;
        }
    }
</script>
{% endblock %}

yong/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>

            {% if current_user.user_id == question.user_id %}
            <div class="my-3">
                <a href="{{ url_for('question.modify', question_id=question.question_id) }}"
                   class="delete btn btn-sm btn-outline-secondary">수정</a>
                <a href="{{ url_for('question.delete', question_id=question.question_id) }}"
                   class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}

        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ answer_list|length }}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer['content'] }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2" style="color:black">
                    {{ answer['user_name'] }}
                </div>
            </div>

                    {% if current_user.user_id == answer['user_id'] %}
                    <div class="my-3">

                        <a href="{{ url_for('answer.delete', answer_id=answer['answer_id']) }}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}

        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.question_id) }}" method="post" class="my-3">
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

yong/templates/question/question_list.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ loop.index+(current_page-1)*5 }}</td>
            <td>
                <a class="text-dark" href="{{ url_for('question.detail', question_id=question['question_id']) }}">{{ question["title"]}}</a>
            </td>

            <td>
                {{ question["user_name"]}}
            </td>

            <td>
                {{ question["time"]|datetime}}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
     <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>





<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="{{url_for('question._list', current_page=current_page-1)}}">이전</a></li>
    {% for page_num in range(start_page,(start_page+page_length)) %}
    {% if page_num==current_page %}
    <li class="page-item active"><a class="page-link" href="{{url_for('question._list', current_page=page_num)}}")>{{page_num}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="{{url_for('question._list', current_page=page_num)}}")>{{page_num}}</a></li>
    {% endif %}
    {% endfor %}
    <li class="page-item"><a class="page-link" href="{{url_for('question._list', current_page=current_page+1)}}">다음</a></li>
  </ul>
</nav>






{% endblock %}